apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bgdk-app
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bgdk/overlays/cluster1
    repoURL: https://github.com/christianh814/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: bgd
        server: https://kubernetes.default.svc
      source:
        path: bgdk/overlays/cluster1
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: master
